tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      #Install aws cli tool
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install      
      
      #Install backend requirements
      cd $THEIA_WORKSPACE_ROOT/backend-flask
      pip3 install -r requirements.txt      
      
      #Install frontend requirements
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i      
      cd $THEIA_WORKSPACE_ROOT

# VSCode extensions
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - redhat.vscode-yaml
